apiVersion: 1
datasources:
- name: prometheus
  type: prometheus
  orgId: 1
  url: http://prometheus:9090
  isDefault: true
  access: proxy
  jsonData:
    timeInterval: "5s"
  version: 1
  editable: true